title: Craft Room Records
email: hello@craftroomrecords.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://craftroomrecords.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
